import { Metadata } from "next"
import { futurbold, roboto } from "./fonts/fonts"
import "./globals.css"

// will apply revalidate on this level and descending levels
// Revalidate: اول ما يفيتش يستني قد ايه عشان يفيتش تاني ، لازم ارفرش عشان اشوف الجديد
// غالبا فيها مشكله في 13.2.4 في البرودكشن موود
// بس اقدر استخدمها مع كل فيتش
export const revalidate = 5

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
  // ⬇️ This is already set by default
  // viewport: "width=device-width, initial-scale=1"
}

type RootLayoutProps_TP = {
  children: React.ReactNode
}
export default function RootLayout({ children }: RootLayoutProps_TP) {
  return (
    <html lang="en" className={`${roboto.className} ${futurbold.variable}`}>
      <body>{children}</body>
    </html>
  )
}
